- NumPy - numerical operations
- Pandas - deal with data manipulation
- Matplotlib - plotting library
- Scikit-learn - machine learning
- Tensorflow or PyTorch - are frameworks for deep learning

## NumPy

- Numerical Python - Num Py
- gives us a fast data type - called Array or `ndarray` -> N-Dimensional Array
- Numpy helps us do math on arrays
    - Data science and analytics?, how it helps?
    - Store data in arrays
    - Implement statistics or other operations
    - Matrix operations - can help in tables, ML and also DL
- numpy is one of the most fundamental libraries in python
- 
- there used to be a disscussion on whether to put numpy inside of python by default
    - creators of python thought that would be too much code to handle 
    - 
- [Learn Numpy from Documentation](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [2]:
#pip install numpy

- Everything we covered so far, was to teach you python and programming
    - is so that you can learn things on you own later
- 

## Arrays
- Array is a homogenous and linear data structure 
    - homogeous - you save `only one type of data` elements inside
    - it has indicies - we can use them to access data
    - 
- if we already have lists in python, why do we need Arrays?
    - Arrays are very **FAST** compared to list
        - reason is not just how numpy was created, but also the fact that we only store single type of data inside arrays
        - 
- Numpy arrays are better at numerical operation than python lists ---> because of **BROADCASTING**

In [ ]:
import numpy as np

# simple array

num_list = [1,2,3,4,5] # python list
num_array = np.array(num_list)  # python list as argument to the array() method
print(num_array)   # [1 2 3 4 5]

num_array # array([1, 2, 3, 4, 5])

# print(num_list) #[1, 2, 3, 4, 5]

# type(num_array) # numpy.ndarray

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
# homogenity of arrays

num_list = [1, 2.0,"idrees", 4, 5]    # multiple types of data

num_array = np.array(num_list)  # array will lose its special powers
# you can create an array like this
# dtype='<U32' ---> this data type says that --- this array won't be as fast
# array will lose its special powers of speed and memory optimization

num_array


array(['1', '2.0', 'idrees', '4', '5'], dtype='<U32')

In [ ]:
num_list = [1,2,3,4,5,6,7,8,9]     # [10,20,30,40,50,60,70,80,90]
num_list10 = []

for num in num_list:
     num_list10.append(num*10)


num_list10 = [x*10 for x in num_list]
print(num_list10)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
# Broadcasting

num_array = np.array(num_list)
num_array   # array([1, 2, 3, 4, 5, 6, 7, 8, 9])

num_array * 10


# no need of the for loop for Numpy arrays

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

- This is called **BROADCASTING**
    - one of the special things about Numpy
- numpy lets us do numerical operations really well

### Exercise:  (understand performance difference between the two)

1. Create a python List ---> `N = 10000` then `listname = list(range(N))`
2. Create an numpy array
3. We observe the size of both ---> use the `sys` module and `sys.getsizeof()`
4. Use time module to time the amount of time taken to do multiplication
    - `start_time = time.time() # current time`
    - your list *2 ---> execute this 
    - end_time = time.time()
    - list_time = end_time - start_time ---> amount of time took for a list to multiply 2 with all the members
5. Repeat the step 4 with a array - But simply multiply the array with the list

If not much difference please increase `N` to 1000000000

In [28]:
num_4 = np.array([1, 2, 3, 4])
num_3 = np.array([10, 10, 20])

#num_3 * num_4 # Error: operands could not be broadcast together with shapes (3,) (4,)

### Shapes and Dimensions

1D array :

2D array :

3D array : 

...